### PR TITLE
Homepage improvements & various fixes

### PR DESCRIPTION
**Pull request by frozenpandaman**
The current index page is outdated (old logo & favicon, broken mod phone #) and needed a few minor visual tweaks… hopefully it's a bit better now! Also various visual fixes for the site-wide header & footer along with a few other small things.

screen shot 2016-09-13 at 03 40 31

### CODE REVIEW

**Comment by jthemphill** [comment]
noice

**Comment by frozenpandaman** [comment]
i think that's the best reply i've ever received

**Comment by frozenpandaman** [comment]
@jthemphill Also, at some point the static files need to be re-compiled (for the .scss changes to take effect).

**Comment by jthemphill** [comment]
fuuuck sass is broken on the server

**Comment by frozenpandaman** [comment]
omg

how 2 fix

**Pull request merged**
